#pain
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=false

org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true
org.gradle.java.installations.paths=

# Gradle
#org.gradle.jvmargs=-Xmx3G
#org.gradle.daemon=true
#org.gradle.parallel=true

# Project
version=2.1.12
group=com.axalotl.async
java_version=17

# ParchmentMC (see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions)
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Mixin
mixin_version=0.8.5
mixin_min_version=0.8.5
mixinextras_version=0.5.4
mixinsquared_version=0.1.2-beta.4

# Common
minecraft_version=1.20.1
mod_name=TickWeave
archive_name=tickweave
mod_authors=Kltyton, HariMT, Axalotl, Alchemy, Bliss, FurryMileon, Grider, jediminer543
mod_id=tickweave
license=GPL-3.0-only
credits=
description=Async entity processing with multi-threading for smoother server performance.
minecraft_version_range=[1.20.1]

# Fabric
fabric_version=0.92.6+1.20.1
fabric_loader_version=0.19.3
permission_api=0.6.0

# Forge
forge_version=47.4.16
forge_loader_version_range=[47,)
forge_mixins=[tickweave.common.mixins.json,tickweave.forge.mixins.json]

# Optional dependencies
harium_version=1.0.0

#org.gradle.java.installations.auto-download=false
#org.gradle.java.installations.auto-detect=false
